
export GPR_PROJECT_PATH=${CURDIR}

all:
	getbuildorder -n com.hcm.hcmenterprisebus.common.topics.trainers.fcdsimulatortarget.idl/com_hcm_hcmenterprisebus_common_topics_trainers_fcdsimulatortarget.gpr >result.txt 2>&1

